/**
 * CopilotKit AG-UI Chat Interface
 *
 * Uses CopilotKit's AG-UI protocol for proper streaming and message handling.
 */

import { useState, useEffect } from "react";
import { CopilotKit, useCopilotAction } from "@copilotkit/react-core";
import { CopilotSidebar } from "@copilotkit/react-ui";
import "@copilotkit/react-ui/styles.css";
import { A2UIRenderer } from "./A2UIRenderer";
import { useTheme } from "../contexts/ThemeContext";

interface DashboardHistoryItem {
  id: string;
  title: string;
  query: string;
  a2ui: string;
  timestamp: Date;
}

const QUICK_EXAMPLES = [
  { label: "📊 Sales Dashboard", query: "Show me a sales dashboard template 1", icon: "📊" },
  { label: "💻 IT Assets Grid", query: "Build IT asset tracking dashboard template 3", icon: "💻" },
  { label: "👥 Customer Analytics", query: "Create customer analytics dashboard template 2", icon: "👥" },
  { label: "☁️ Cloud Resources", query: "Show Azure/AWS resource dashboard", icon: "☁️" },
  { label: "📝 License Tracker", query: "Create software license dashboard", icon: "📝" },
  { label: "📋 Support Form", query: "Generate a ticket logging form", icon: "📋" },
];

function CopilotKitInner() {
  const { theme, toggleTheme } = useTheme();
  const [a2uiData, setA2uiData] = useState<string | null>(null);
  const [currentDashboardTitle, setCurrentDashboardTitle] = useState<string>("");
  const [history, setHistory] = useState<DashboardHistoryItem[]>([]);
  const [showHistory, setShowHistory] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);
  const [loading, setLoading] = useState(false);

  // Register action to receive A2UI data from the agent
  useCopilotAction({
    name: "renderA2UI",
    description: "Renders A2UI components generated by the agent",
    parameters: [
      {
        name: "a2ui_jsonl",
        type: "string",
        description: "The A2UI JSONL data to render",
        required: true,
      },
      {
        name: "title",
        type: "string",
        description: "Dashboard title",
        required: false,
      },
    ],
    handler: async ({ a2ui_jsonl, title }) => {
      console.log("[CopilotKit] Received A2UI data:", { a2ui_jsonl, title });

      setA2uiData(a2ui_jsonl);
      setLoading(false);

      const dashboardTitle = title || extractDashboardTitle(a2ui_jsonl);
      setCurrentDashboardTitle(dashboardTitle);

      // Add to history
      const historyItem: DashboardHistoryItem = {
        id: Date.now().toString(),
        title: dashboardTitle,
        query: "", // CopilotKit doesn't give us the original query easily
        a2ui: a2ui_jsonl,
        timestamp: new Date(),
      };

      setHistory((prev) => {
        const newHistory = [historyItem, ...prev].slice(0, 10);
        return newHistory;
      });

      return "A2UI rendered successfully";
    },
  });

  const extractDashboardTitle = (jsonl: string): string => {
    try {
      const lines = jsonl.trim().split("\n");
      const firstLine = JSON.parse(lines[0]);
      if (firstLine.surfaceUpdate?.components) {
        const titleComp = firstLine.surfaceUpdate.components.find(
          (c: any) => c.component?.Text?.usage_hint === "title"
        );
        if (titleComp) {
          return titleComp.component.Text.text.literalString || "Dashboard";
        }
      }
    } catch (e) {
      console.error("Failed to extract title:", e);
    }
    return "Dashboard";
  };

  const handleExportJSON = () => {
    if (!a2uiData) return;

    try {
      const lines = a2uiData.trim().split("\n").filter(line => line.trim());
      const parsedLines = lines.map(line => JSON.parse(line));
      const formattedData = parsedLines.map(obj => JSON.stringify(obj, null, 2)).join("\n\n");

      const dataBlob = new Blob([formattedData], { type: "application/json" });
      const url = URL.createObjectURL(dataBlob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${currentDashboardTitle.replace(/\s+/g, "_").toLowerCase()}_${Date.now()}.jsonl`;
      link.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Failed to export:", err);
    }
  };

  const handleCopyJSON = async () => {
    if (!a2uiData) return;

    try {
      const lines = a2uiData.trim().split("\n").filter(line => line.trim());
      const parsedLines = lines.map(line => JSON.parse(line));
      const formattedData = parsedLines.map(obj => JSON.stringify(obj, null, 2)).join("\n\n");

      await navigator.clipboard.writeText(formattedData);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const loadHistoryItem = (item: DashboardHistoryItem) => {
    setA2uiData(item.a2ui);
    setCurrentDashboardTitle(item.title);
  };

  return (
    <div className="simple-chat-interface">
      <div className="chat-container">
        {/* Header */}
        <div className="chat-header">
          <div className="header-content">
            <div>
              <h1>ChatLangA2UI</h1>
              <p>AI-powered dynamic UI generation with Claude & A2UI (AG-UI Protocol)</p>
            </div>
            <div style={{ display: "flex", gap: "12px", alignItems: "center" }}>
              <button
                className="theme-toggle"
                onClick={toggleTheme}
                title={`Switch to ${theme === "light" ? "dark" : "light"} mode`}
                style={{
                  padding: "8px 16px",
                  fontSize: "20px",
                  background: "transparent",
                  border: "2px solid var(--border-color)",
                  borderRadius: "8px",
                  cursor: "pointer",
                  transition: "all 0.3s ease",
                }}
              >
                {theme === "light" ? "🌙" : "☀️"}
              </button>
              <button
                className="history-toggle"
                onClick={() => setShowHistory(!showHistory)}
                title="Dashboard History"
              >
                📚 History {history.length > 0 && `(${history.length})`}
              </button>
            </div>
          </div>
        </div>

        {/* Main Content Area */}
        <div className="chat-main">
          {/* Dashboard History Sidebar */}
          {showHistory && (
            <div className="history-sidebar">
              <h3>Recent Dashboards</h3>
              {history.length === 0 ? (
                <p className="history-empty">No dashboards yet</p>
              ) : (
                <div className="history-list">
                  {history.map((item) => (
                    <div
                      key={item.id}
                      className="history-item"
                      onClick={() => loadHistoryItem(item)}
                    >
                      <div className="history-item-title">{item.title}</div>
                      <div className="history-item-time">
                        {item.timestamp.toLocaleTimeString()}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* A2UI Render Area */}
          <div className="a2ui-area">
            <div className="a2ui-area-header">
              <div>
                <h3>Generated UI {currentDashboardTitle && `- ${currentDashboardTitle}`}</h3>
                <p>Dynamic components rendered from AI responses via AG-UI Protocol</p>
              </div>
              {a2uiData && (
                <div className="export-buttons">
                  <button
                    onClick={handleCopyJSON}
                    className="export-btn"
                    title="Copy A2UI JSON to clipboard"
                  >
                    {copySuccess ? "✓ Copied!" : "📋 Copy JSON"}
                  </button>
                  <button
                    onClick={handleExportJSON}
                    className="export-btn"
                    title="Download A2UI JSON file"
                  >
                    💾 Export
                  </button>
                </div>
              )}
            </div>
            <div className="a2ui-content">
              {loading ? (
                <div className="loading-skeleton">
                  <div className="skeleton-header"></div>
                  <div className="skeleton-cards">
                    <div className="skeleton-card"></div>
                    <div className="skeleton-card"></div>
                    <div className="skeleton-card"></div>
                    <div className="skeleton-card"></div>
                  </div>
                  <div className="skeleton-chart"></div>
                  <div className="skeleton-table">
                    <div className="skeleton-table-row"></div>
                    <div className="skeleton-table-row"></div>
                    <div className="skeleton-table-row"></div>
                  </div>
                  <p className="loading-text">✨ Generating dashboard...</p>
                </div>
              ) : a2uiData ? (
                <A2UIRenderer data={a2uiData} />
              ) : (
                <div className="a2ui-placeholder">
                  <p>💬 Start a conversation to see dynamic UI appear here</p>
                  <div className="example-prompts">
                    <h4>Try asking:</h4>
                    <ul>
                      <li>"Show me a sales dashboard"</li>
                      <li>"Create a revenue chart"</li>
                      <li>"Generate a contact form"</li>
                    </ul>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* CopilotKit Chat Sidebar */}
          <CopilotSidebar
            defaultOpen={true}
            className="chat-area"
            labels={{
              initial: "Welcome! Ask me to create dashboards, charts, tables, or forms.",
            }}
          >
            <div style={{ padding: "12px" }}>
              <h4 style={{ margin: "0 0 12px 0", fontSize: "14px", color: "var(--text-secondary)" }}>
                Quick Examples:
              </h4>
              <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                {QUICK_EXAMPLES.map((example, idx) => (
                  <button
                    key={idx}
                    className="example-btn"
                    onClick={() => {
                      setLoading(true);
                      // CopilotKit will handle sending this message
                    }}
                    style={{ textAlign: "left", width: "100%" }}
                  >
                    {example.label}
                  </button>
                ))}
              </div>
            </div>
          </CopilotSidebar>
        </div>
      </div>
    </div>
  );
}

export function CopilotKitChatInterface() {
  return (
    <CopilotKit
      runtimeUrl="http://localhost:8123/copilotkit"
      agent="dashboard_agent"
    >
      <CopilotKitInner />
    </CopilotKit>
  );
}
